if(NOT DEFINED PROGRAM OR NOT DEFINED CARGO OR NOT DEFINED PYTHON OR NOT DEFINED REPOSITORY_ROOT OR NOT DEFINED SCENARIO OR NOT DEFINED SUMMARY OR NOT DEFINED VCD OR NOT DEFINED FPGA_TRACE OR NOT DEFINED BEHAVIORAL_TRACE OR NOT DEFINED COMPARISON_REPORT)
    message(FATAL_ERROR "PROGRAM, CARGO, PYTHON, REPOSITORY_ROOT, SCENARIO, SUMMARY, VCD, FPGA_TRACE, BEHAVIORAL_TRACE, and COMPARISON_REPORT are required")
endif()
if(NOT DEFINED COMPARISON_MAX_MISMATCH_OBSERVATIONS)
    set(COMPARISON_MAX_MISMATCH_OBSERVATIONS 0)
endif()

execute_process(
    COMMAND "${CARGO}" run --locked -p mcs4-system --bin mcs4-common-stimulus -- --stimulus "${SCENARIO}"
    WORKING_DIRECTORY "${REPOSITORY_ROOT}"
    RESULT_VARIABLE behavioral_result
    OUTPUT_FILE "${BEHAVIORAL_TRACE}"
    ERROR_VARIABLE behavioral_error
)
if(NOT behavioral_result EQUAL 0)
    message(FATAL_ERROR "common behavioral scenario failed: ${behavioral_error}")
endif()

execute_process(
    COMMAND "${PROGRAM}" --headless --scenario "${SCENARIO}" --summary "${SUMMARY}" --vcd "${VCD}" --trace-frames "${FPGA_TRACE}"
    WORKING_DIRECTORY "${REPOSITORY_ROOT}"
    RESULT_VARIABLE fpga_result
    OUTPUT_VARIABLE fpga_output
    ERROR_VARIABLE fpga_error
)
if(NOT fpga_result EQUAL 0)
    message(FATAL_ERROR "common FPGA scenario failed: ${fpga_error}")
endif()

foreach(required_file IN ITEMS "${SUMMARY}" "${VCD}" "${FPGA_TRACE}" "${BEHAVIORAL_TRACE}")
    if(NOT EXISTS "${required_file}")
        message(FATAL_ERROR "common scenario did not write ${required_file}")
    endif()
endforeach()
file(SIZE "${VCD}" vcd_size)
if(vcd_size LESS 128)
    message(FATAL_ERROR "common FPGA scenario wrote an unexpectedly small VCD")
endif()

file(READ "${SCENARIO}" scenario_json)
string(JSON action_count LENGTH "${scenario_json}" actions)
if(NOT action_count)
    message(FATAL_ERROR "common scenario does not expose any actions")
endif()
set(expected_frame_count 0)
math(EXPR action_max_index "${action_count} - 1")
if(action_max_index LESS 0)
    message(FATAL_ERROR "common scenario action count is invalid")
endif()
foreach(action_index RANGE 0 "${action_max_index}")
    string(JSON action_op GET "${scenario_json}" actions "${action_index}" op)
    if(action_op STREQUAL "run_phases")
        string(JSON action_steps GET "${scenario_json}" actions "${action_index}" value)
        math(EXPR expected_frame_count "${expected_frame_count} + ${action_steps}")
    endif()
endforeach()
if(expected_frame_count LESS 1)
    message(FATAL_ERROR "common scenario does not request any phase observations")
endif()

file(STRINGS "${FPGA_TRACE}" fpga_lines)
file(STRINGS "${BEHAVIORAL_TRACE}" behavioral_lines)
list(LENGTH fpga_lines fpga_count)
list(LENGTH behavioral_lines behavioral_count)
if(NOT fpga_count EQUAL expected_frame_count OR NOT behavioral_count EQUAL expected_frame_count)
    message(FATAL_ERROR "common scenario did not retain one frame per requested phase")
endif()
list(GET fpga_lines 0 fpga_frame)
list(GET behavioral_lines 0 behavioral_frame)
string(JSON fpga_hash GET "${fpga_frame}" provenance stimulus_sha256)
string(JSON behavioral_hash GET "${behavioral_frame}" provenance stimulus_sha256)
string(JSON fpga_kind GET "${fpga_frame}" provenance stimulus_kind)
string(JSON behavioral_kind GET "${behavioral_frame}" provenance stimulus_kind)
if(fpga_hash STREQUAL "" OR NOT fpga_hash STREQUAL behavioral_hash)
    message(FATAL_ERROR "common adapters did not retain the same stimulus hash")
endif()
if(NOT fpga_kind STREQUAL "scenario-json" OR NOT behavioral_kind STREQUAL "scenario-json")
    message(FATAL_ERROR "common adapters did not identify the shared scenario representation")
endif()
string(JSON fpga_pc_path GET "${fpga_frame}" signals 4 path)
string(JSON behavioral_pc_path GET "${behavioral_frame}" signals 4 path)
if(NOT fpga_pc_path STREQUAL "mcs4.cpu.pc" OR NOT behavioral_pc_path STREQUAL "mcs4.cpu.pc")
    message(FATAL_ERROR "common adapters did not expose the mapped MCS-4 program counter")
endif()

execute_process(
    COMMAND "${PYTHON}" "${REPOSITORY_ROOT}/scripts/compare_common_stimulus_traces.py" --behavioral "${BEHAVIORAL_TRACE}" --fpga "${FPGA_TRACE}" --report "${COMPARISON_REPORT}" --phase-map identity --max-mismatch-observations "${COMPARISON_MAX_MISMATCH_OBSERVATIONS}"
    WORKING_DIRECTORY "${REPOSITORY_ROOT}"
    RESULT_VARIABLE comparison_result
    ERROR_VARIABLE comparison_error
)
if(NOT comparison_result EQUAL 0)
    message(FATAL_ERROR "common trace comparison failed: ${comparison_error}")
endif()
if(NOT EXISTS "${COMPARISON_REPORT}")
    message(FATAL_ERROR "common trace comparison did not write a report")
endif()
file(READ "${COMPARISON_REPORT}" comparison_json)
string(JSON comparison_exact_equivalence GET "${comparison_json}" exact_equivalence)
string(JSON comparison_within_budget GET "${comparison_json}" within_mismatch_budget)
string(JSON comparison_shared_length LENGTH "${comparison_json}" shared_paths)
string(JSON comparison_mismatches GET "${comparison_json}" mismatching_observations)
string(JSON comparison_budget GET "${comparison_json}" max_mismatch_observations)
string(JSON comparison_phase_map GET "${comparison_json}" phase_map)
if(NOT comparison_shared_length GREATER 0)
    message(FATAL_ERROR "common trace report has no shared signals")
endif()
if(NOT comparison_phase_map STREQUAL "identity")
    message(FATAL_ERROR "common trace comparison used unexpected phase map ${comparison_phase_map}")
endif()
if(NOT comparison_mismatches MATCHES "^[0-9]+$")
    message(FATAL_ERROR "common trace comparison did not write a numeric mismatch count")
endif()
if(NOT comparison_budget MATCHES "^[0-9]+$")
    message(FATAL_ERROR "common trace comparison did not write a numeric mismatch budget")
endif()
if(NOT comparison_within_budget)
    message(FATAL_ERROR "common trace report exceeded mismatch budget: ${comparison_mismatches} > ${comparison_budget}")
endif()
if(comparison_budget STREQUAL "0" AND NOT comparison_exact_equivalence)
    message(FATAL_ERROR "zero-budget common trace report did not establish exact equivalence")
endif()
if(DEFINED REQUIRED_ACTIVE_BEHAVIORAL_SIGNAL)
    string(JSON behavioral_active_count ERROR_VARIABLE behavioral_active_error GET "${comparison_json}" behavioral_active_by_path "${REQUIRED_ACTIVE_BEHAVIORAL_SIGNAL}")
    if(behavioral_active_error OR NOT behavioral_active_count MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "common behavioral trace did not activate ${REQUIRED_ACTIVE_BEHAVIORAL_SIGNAL}")
    endif()
endif()
if(DEFINED REQUIRED_ACTIVE_FPGA_SIGNAL)
    string(JSON fpga_active_count ERROR_VARIABLE fpga_active_error GET "${comparison_json}" fpga_active_by_path "${REQUIRED_ACTIVE_FPGA_SIGNAL}")
    if(fpga_active_error OR NOT fpga_active_count MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "common FPGA trace did not activate ${REQUIRED_ACTIVE_FPGA_SIGNAL}")
    endif()
endif()
message(STATUS "${fpga_output}")
