if(NOT DEFINED PROGRAM OR NOT DEFINED SCENARIO OR NOT DEFINED SUMMARY OR NOT DEFINED VCD OR NOT DEFINED TRACE_FRAMES)
    message(FATAL_ERROR "PROGRAM, SCENARIO, SUMMARY, VCD, and TRACE_FRAMES are required")
endif()

execute_process(
    COMMAND "${PROGRAM}" --headless --scenario "${SCENARIO}" --summary "${SUMMARY}" --vcd "${VCD}" --trace-frames "${TRACE_FRAMES}"
    RESULT_VARIABLE scenario_result
    OUTPUT_VARIABLE scenario_output
    ERROR_VARIABLE scenario_error
)
if(NOT scenario_result EQUAL 0)
    message(FATAL_ERROR "headless system scenario failed: ${scenario_error}")
endif()
foreach(required_file IN ITEMS "${SUMMARY}" "${VCD}" "${TRACE_FRAMES}")
    if(NOT EXISTS "${required_file}")
        message(FATAL_ERROR "headless system scenario did not write ${required_file}")
    endif()
endforeach()
file(SIZE "${VCD}" vcd_size)
if(vcd_size LESS 128)
    message(FATAL_ERROR "headless system scenario wrote an unexpectedly small VCD")
endif()

file(READ "${SUMMARY}" summary_json)
string(JSON module GET "${summary_json}" module)
string(JSON wmp_strobes GET "${summary_json}" wmp_strobes)
string(JSON saw_nonidle_bus GET "${summary_json}" saw_nonidle_bus)
string(JSON saw_phi_overlap GET "${summary_json}" saw_phi_overlap)
string(JSON saw_bus_contention GET "${summary_json}" saw_bus_contention)
string(JSON trace_frame_count GET "${summary_json}" trace_frame_count)
if(NOT module STREQUAL "mcs4_system_sim_top")
    message(FATAL_ERROR "unexpected system module: ${module}")
endif()
if(wmp_strobes LESS 2)
    message(FATAL_ERROR "system scenario observed fewer than two WMP strobes")
endif()
if(NOT saw_nonidle_bus)
    message(FATAL_ERROR "system scenario did not observe a non-idle bus")
endif()
if(saw_phi_overlap)
    message(FATAL_ERROR "system scenario observed overlapping phi phases")
endif()
if(saw_bus_contention)
    message(FATAL_ERROR "system scenario observed bus contention")
endif()

file(STRINGS "${TRACE_FRAMES}" trace_frame_lines)
list(LENGTH trace_frame_lines trace_frame_line_count)
if(NOT trace_frame_line_count EQUAL trace_frame_count)
    message(FATAL_ERROR "trace-frame count does not match the summary")
endif()
if(trace_frame_line_count LESS 5)
    message(FATAL_ERROR "system scenario retained too few trace frames")
endif()
list(GET trace_frame_lines 0 first_trace_frame)
string(JSON trace_schema GET "${first_trace_frame}" schema_version)
string(JSON trace_backend GET "${first_trace_frame}" provenance backend)
string(JSON trace_fidelity GET "${first_trace_frame}" provenance fidelity)
string(JSON trace_model GET "${first_trace_frame}" provenance model_id)
string(JSON trace_stimulus GET "${first_trace_frame}" provenance stimulus_sha256)
string(JSON trace_stimulus_kind GET "${first_trace_frame}" provenance stimulus_kind)
string(JSON trace_phase_kind GET "${first_trace_frame}" signals 0 value kind)
string(JSON trace_phase_width GET "${first_trace_frame}" signals 0 value width)
if(NOT trace_schema EQUAL 1)
    message(FATAL_ERROR "system trace frame schema is not version 1")
endif()
if(NOT trace_backend STREQUAL "verilator" OR NOT trace_fidelity STREQUAL "fpga")
    message(FATAL_ERROR "system trace frame provenance does not identify Verilator FPGA evidence")
endif()
if(NOT trace_model STREQUAL "mcs4-system-fpga-verilator")
    message(FATAL_ERROR "unexpected system trace model identity: ${trace_model}")
endif()
if(trace_stimulus STREQUAL "")
    message(FATAL_ERROR "system trace frame does not declare a scenario stimulus hash")
endif()
if(NOT trace_stimulus_kind STREQUAL "scenario-json")
    message(FATAL_ERROR "system trace frame does not declare the scenario stimulus representation")
endif()
if(NOT trace_phase_kind STREQUAL "bits" OR NOT trace_phase_width EQUAL 3)
    message(FATAL_ERROR "system trace frame does not expose the mapped phase signal")
endif()
message(STATUS "${scenario_output}")
