if(NOT DEFINED PROGRAM OR NOT DEFINED SCENARIO OR NOT DEFINED SUMMARY OR NOT DEFINED VCD OR NOT DEFINED TRACE_FRAMES)
    message(FATAL_ERROR "PROGRAM, SCENARIO, SUMMARY, VCD, and TRACE_FRAMES are required")
endif()

execute_process(
    COMMAND "${PROGRAM}" --headless --scenario "${SCENARIO}" --summary "${SUMMARY}" --vcd "${VCD}" --trace-frames "${TRACE_FRAMES}"
    RESULT_VARIABLE scenario_result
    OUTPUT_VARIABLE scenario_output
    ERROR_VARIABLE scenario_error
)
if(NOT scenario_result EQUAL 0)
    message(FATAL_ERROR "headless scenario failed: ${scenario_error}")
endif()
if(NOT EXISTS "${SUMMARY}")
    message(FATAL_ERROR "headless scenario did not write a summary")
endif()
if(NOT EXISTS "${VCD}")
    message(FATAL_ERROR "headless scenario did not write a VCD")
endif()
if(NOT EXISTS "${TRACE_FRAMES}")
    message(FATAL_ERROR "headless scenario did not write trace frames")
endif()
file(SIZE "${VCD}" vcd_size)
if(vcd_size LESS 128)
    message(FATAL_ERROR "headless scenario wrote an unexpectedly small VCD")
endif()
file(READ "${SUMMARY}" summary_json)
string(JSON parallel_out GET "${summary_json}" parallel_out)
string(JSON system_cycles GET "${summary_json}" system_cycles)
if(NOT parallel_out EQUAL 5)
    message(FATAL_ERROR "expected parallel_out=5, got ${parallel_out}")
endif()
if(NOT system_cycles EQUAL 9)
    message(FATAL_ERROR "expected system_cycles=9, got ${system_cycles}")
endif()
string(JSON trace_frame_count GET "${summary_json}" trace_frame_count)
if(NOT trace_frame_count EQUAL 10)
    message(FATAL_ERROR "expected 10 trace frames, got ${trace_frame_count}")
endif()
file(STRINGS "${TRACE_FRAMES}" trace_frame_lines)
list(LENGTH trace_frame_lines trace_frame_line_count)
if(NOT trace_frame_line_count EQUAL 10)
    message(FATAL_ERROR "expected 10 trace-frame JSONL lines, got ${trace_frame_line_count}")
endif()
list(GET trace_frame_lines 0 first_trace_frame)
string(JSON trace_schema GET "${first_trace_frame}" schema_version)
string(JSON trace_backend GET "${first_trace_frame}" provenance backend)
string(JSON trace_fidelity GET "${first_trace_frame}" provenance fidelity)
string(JSON trace_model GET "${first_trace_frame}" provenance model_id)
string(JSON trace_parallel_width GET "${first_trace_frame}" signals 3 value width)
if(NOT trace_schema EQUAL 1)
    message(FATAL_ERROR "trace frame schema is not version 1")
endif()
if(NOT trace_backend STREQUAL "verilator" OR NOT trace_fidelity STREQUAL "fpga")
    message(FATAL_ERROR "trace frame provenance does not identify the Verilator FPGA adapter")
endif()
if(NOT trace_model STREQUAL "i4003-fpga-verilator")
    message(FATAL_ERROR "trace frame model identity is unexpected: ${trace_model}")
endif()
if(NOT trace_parallel_width EQUAL 10)
    message(FATAL_ERROR "parallel output trace width is not 10 bits")
endif()
message(STATUS "${scenario_output}")
