[package]
name = "mcs4-core"
description = "Core simulation kernel for MCS-4/MCS-40"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
modular-bitfield.workspace = true
smallvec.workspace = true
serde.workspace = true
rkyv.workspace = true
bytemuck.workspace = true
zerocopy.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
