//! Loader for `netlist_v0` JSON evidence outputs.
//!
//! `netlist_v0` files are generated by `scripts/extract_netlist_v0.py` and live under
//! `docs/evidence/netlists_v0/`. These are *layout-mask* connectivity outputs; they are not
//! (yet) a full analyzer-grade schematic↔layout reconciled netlist.

use std::path::Path;

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0 {
    pub chip: String,
    pub schema: NetlistV0Schema,
    pub inputs: NetlistV0Inputs,
    pub params: NetlistV0Params,
    pub counts: NetlistV0Counts,
    pub signals: NetlistV0Signals,
    pub devices: NetlistV0Devices,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Schema {
    pub version: u32,
    pub description: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Inputs {
    pub metal_bmp: String,
    pub vias_bmp: String,
    pub poly_bmp: String,
    pub diffusion_bmp: String,
    pub contacts_bmp: Option<String>,
    pub schematic_bmp: String,
    pub signals_txt: String,
    pub transistors_json: String,
    pub sha256: NetlistV0Sha256,
    pub layout_shape: NetlistV0Shape,
    pub schematic_shape: NetlistV0Shape,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Sha256 {
    pub metal: String,
    pub vias: String,
    pub poly: String,
    pub diffusion: String,
    pub contacts: Option<String>,
    pub schematic_bmp: String,
    pub signals_txt: String,
    pub transistors_json: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Shape {
    pub h: u32,
    pub w: u32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Params {
    pub threshold: u32,
    pub polarity: String,
    pub dilate: i32,
    pub diffusion_split: bool,
    pub pad: u32,
    pub stitch_max_labels: u32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Counts {
    pub components: NetlistV0ComponentCounts,
    pub nodes: u32,
    pub stitches: NetlistV0StitchCounts,
    pub stitches_ambiguous: NetlistV0StitchCounts,
    pub transistors_kept: u32,
    pub transistors_ambiguous: u32,
    pub signals_points: u32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0ComponentCounts {
    pub metal: u32,
    pub poly: u32,
    pub diffusion: u32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0StitchCounts {
    pub vias: u32,
    pub contacts: u32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Signals {
    pub space: String,
    pub schematic_reference_points: Vec<NetlistV0SignalPoint>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0SignalPoint {
    pub x: i32,
    pub y: i32,
    pub name: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Devices {
    pub transistors: Vec<NetlistV0Transistor>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Transistor {
    pub kind: String,
    pub gate_node: u32,
    pub a_node: u32,
    pub b_node: u32,
    pub bbox: NetlistV0Bbox,
    pub source_component: NetlistV0SourceComponent,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0Bbox {
    pub x: u32,
    pub y: u32,
    pub w: u32,
    pub h: u32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetlistV0SourceComponent {
    pub poly_diff_id: u32,
}

pub fn load_netlist_v0(path: impl AsRef<Path>) -> Result<NetlistV0, Box<dyn std::error::Error + Send + Sync>> {
    let text = std::fs::read_to_string(path)?;
    let netlist: NetlistV0 = serde_json::from_str(&text)?;
    Ok(netlist)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_committed_4004_netlist_v0() {
        let repo_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..");
        let path = repo_root.join("docs/evidence/netlists_v0/4004_netlist_v0.json");
        let net = load_netlist_v0(&path).expect("load netlist_v0 json");
        assert_eq!(net.chip, "4004");
        assert_eq!(net.schema.version, 0);
        assert_eq!(net.signals.space, "schematic");
        assert!(net.counts.nodes > 1000, "nodes too small: {}", net.counts.nodes);
        assert!(!net.devices.transistors.is_empty(), "expected some transistors");
    }
}
