[package]
name = "mcs4-periph"
description = "Peripheral device emulation for MCS-4 systems"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
mcs4-core = { path = "../mcs4-core" }
mcs4-bus = { path = "../mcs4-bus" }
mcs4-chips = { path = "../mcs4-chips" }
