#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT_DIR/docs/TODO.md"

scan_with_rg() {
  rg -n --no-heading \
    -S --hidden \
    --glob '!.git/*' \
    --glob '!target/*' \
    --glob '!coverage/*' \
    --glob '!mcs4-emu/target/*' \
    --glob '!docs/evidence/ocr/*' \
    --glob '!docs/emulators/*' \
    -e "\\b(TODO|FIXME|XXX)\\b" \
    "$ROOT_DIR"
}

scan_with_grep() {
  grep -RIn --exclude-dir=.git --exclude-dir=target --exclude-dir=coverage --exclude-dir=mcs4-emu/target \
    --exclude-dir=docs/evidence/ocr --exclude-dir=docs/emulators \
    -e "TODO" -e "FIXME" -e "XXX" \
    "$ROOT_DIR" || true
}

{
  echo "# TODO / FIXME / XXX"
  echo
  echo "Generated by \`scripts/todo_scan.sh\`. Do not edit by hand."
  echo
  echo "## Current Findings"
  echo

  if command -v rg >/dev/null 2>&1; then
    scan_with_rg | sed "s|$ROOT_DIR/||" | sort
  else
    scan_with_grep | sed "s|$ROOT_DIR/||" | sort
  fi
} >"$OUT"

echo "Wrote $OUT"
