[package]
name = "mcs4-bus"
description = "Bus infrastructure for MCS-4 emulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
mcs4-core = { path = "../mcs4-core" }
tracing.workspace = true
serde.workspace = true
rkyv.workspace = true
bytemuck.workspace = true
zerocopy.workspace = true
modular-bitfield.workspace = true
